### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by YhVincent** [stepfun-ai/Step-Video-T2V#5]
after initialized the model, when I do inference, I encounter the error "torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 288.00 MiB." 
It seems the model weights are all on the last gpu, so when inferencing, the last gpu ran out of memory.

**Comment by supfisher** [comment]
We use a parallel strategy where the language model encoding user prompts and the VAE decoding are assigned to the last GPU, while the remaining GPUs handle the DiT inference. Therefore, with 8 GPUs, you can set parallel=4 for DiT inference (using ranks 0, 1, 2, and 3). Otherwise, you can place the language model and VAE decoding on a separate machine and set parallel=8 for DiT inference.

**Comment by YhVincent** [comment]
> We use a parallel strategy where the language model encoding user prompts and the VAE decoding are assigned to the last GPU, while the remaining GPUs handle the DiT inference. Therefore, with 8 GPUs, you can set parallel=4 for DiT inference (using ranks 0, 1, 2, and 3). Otherwise, you can place the language model and VAE decoding on a separate machine and set parallel=8 for DiT inference.

Thanks, this works.
